### ISSUE TITLE
Error checker out of sync with edits

### ISSUE THREAD

**Issue by crosjef** [paul-go/Truth#2]
If I change "Decimal" (line 7) to "Deciimal" I expect annotation errors to be generated. I don't see any errors until I change it back to "Decimal" again. Then 3 errors are reported. Now if I change it back to "Deciimal" the errors go away.

[Machine Screw with SKUs.txt](https://github.com/paul-go/Truth/files/2989470/Machine.Screw.with.SKUs.txt)

**Comment by paul-go** [comment]
This is an old issue that I'm reviving.

On loading this file into the latest version of the compiler, I'm getting 766 errors. I haven't checked all of them, but most of them seem to be coming up because the file is relying on the unimplemented bounded contravariance feature (where types that are matchable by a pattern flow downwards through the graph of abstraction). The work-around for this issue until this feature lands is to duplicate each pattern at each level of abstraction, such as:

```
Decimal
/the-decimal-pattern : Decimal

mm : Decimal
/the-decimal-pattern : mm
```

**Comment by crosjef** [comment]
Verified this is working as expected
[Deciimal (Issue 2).txt](https://github.com/paul-go/Truth/files/3162487/Deciimal.Issue.2.txt)
